### ISSUE TITLE
Design Docs Review

### ISSUE THREAD

**Issue by kkossally** [leon-i/ViewTube#1]
- [x] Mention that this is a YouTube clone on your wiki's home page.

- [x] Likes and search should be separate MVPs. The dashboard and channel should be two separate, more fleshed out bonus MVPs. Add more bonus MVPs to fill out your clone's core functionality.

- [x] Add a search component to your frontend routes and a custom search controller action to your backend routes.

**Comment by leon-i** [comment]
Did all 3, unsure about search for users/user channels though, so I put it as a bonus in the MVPs
